# -*- coding: utf-8 -*-
"""dataVizUsandoPython_Mod4_Leega.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ymyZcdc6bZXfbU5EJew7Zyk7y4MB7JS0

Bibliotecas, Importação Arquivo e Contagem de Campo diagnosis
"""

from google.colab import drive

drive.mount('/content/drive')

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

from google.colab import files

arquivo = files.upload()
nome = list(arquivo.keys())[0]

cancer_data = pd.read_csv(nome)
cancer_data.head()

"""Distribuição de B(benigno) ou M(Maligno)"""

sns.countplot(x="diagnosis", data = cancer_data)
plt.figure

"""Gráficos de Distribuição"""

from os import name
for column in cancer_data:
    if column != 'id' and column != 'diagnosis' and column != ' ':
        sns.displot(x=column,data=cancer_data)
        plt.figure()

"""Outliers

"""

cancer_data = cancer_data.drop(columns=["Unnamed: 32"])

for column in cancer_data:
    if column!='id' and column!='diagnosis':
       sns.boxplot(y=column,data=cancer_data)
       plt.figure()

"""Matriz de Correlação"""

correlation_matrix = cancer_data.corr(numeric_only=True)
plt.figure(figsize=(20,20))
sns.heatmap(correlation_matrix,cbar=True, fmt = '.1f', annot=True, cmap = 'Blues')
plt.savefig('Correlation Heat Map')

"""Instalar SweetViz"""

! pip install SweetViz

#importing sweetviz
import sweetviz as sv
#analyzing the dataset
report_cancer = sv.analyze(cancer_data)
#display the report
report_cancer.show_html('eda_cancer.html')
#